# Generated by Django 3.2.9 on 2021-11-15 21:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, default='', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters.')], verbose_name='Title')),
                ('date', models.DateField(db_index=True, max_length=10, verbose_name='Date')),
                ('jew_types', models.IntegerField(choices=[(1, 'Rings'), (2, 'Earrings'), (3, 'Bracelets')], verbose_name='Types')),
                ('jew_mat', models.IntegerField(choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Platinum')], verbose_name='Materials')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
        ),
    ]
